# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "XenocidePC"
title_separator: "|"
locale: en-AU
logo: "/assets/images/site-logo.jpg"
name: "Jack Li"
email: "xenocidepc@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  The personal site of Jack Li.
github_username: "XenocidePC"
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
# Paginate disabled
# paginate: 5 # amount of posts to show
# paginate_path: /blog/page:num/
timezone: Australia/Sydney # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jack Li"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I'm a first year student at UNSW, studying computer engineering."
  discord: "Xenocide#6723"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/XenocidePC"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/XenocidePC"

footer:
  discord: "Xenocide#6723"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/XenocidePC"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://steamcommunity.com/id/XenocidePC"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Fixes GitHub Metadata warning
# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
github: [metadata]
